#! /bin/bash

KEYBOARD="AT Translated Set 2 keyboard" 

id=$(xinput | grep "$KEYBOARD" | cut -d "=" -f2 | cut -d "[" -f1)

enabled=$(xinput list-props $id | grep "Device Enabled" | awk -F ' ' '{print $4}')

if [ $enabled == 0 ]; then
    xinput set-prop $id "Device Enabled" 1
    echo ⌨
else
    xinput set-prop $id "Device Enabled" 0
    echo !⌨
fi
