CONFIG(debug, debug|release) {
    CONFIG_NAME = Debug
} else {
    CONFIG_NAME = Release
    DEFINES += BUILD_RELEASE
}

RCC_DIR = build/$$CONFIG_NAME
UI_DIR = build/$$CONFIG_NAME
MOC_DIR = build/$$CONFIG_NAME
OBJECTS_DIR = build/$$CONFIG_NAME
DESTDIR = build/$$CONFIG_NAME

#QMAKE_CXXFLAGS_RELEASE -= -O
#QMAKE_CXXFLAGS_RELEASE -= -O1
#QMAKE_CXXFLAGS_RELEASE -= -O2
#QMAKE_CXXFLAGS_RELEASE *= -Os

#QMAKE_CXXFLAGS += -D_GLIBCXX_USE_CXX11_ABI=0
